// ----------------------------------------------------------------------------------------
// This file has been automatically generated by a tool and should not be changed manually.
// ----------------------------------------------------------------------------------------
namespace Sirenix.OdinInspector.GeneratedEditors
{
    extern alias Assembly4bd54c5c7a3f4920b37fe7d533cf59d9;
    extern alias Assembly5b193b5534114185a33ae42996dd4366;
    extern alias Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3;
    extern alias Assembly6fa948118b9b4ba8a12ca777b979e390;
    extern alias Assembly6826020b926d45a5b887abb48d4934e7;
    using System.Runtime.CompilerServices;
    using UnityEditor;
    
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::Ballistic), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_Ballistic_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::CharacterMotion), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_CharacterMotion_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::CoroutineManage), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_CoroutineManage_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::Follow), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_Follow_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::LineRandererControl), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_LineRandererControl_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::LoadMap), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_LoadMap_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::Looper), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_Looper_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::MapDrawer), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_MapDrawer_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::MapEditor), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_MapEditor_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::NeuralMono), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_NeuralMono_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::SkinnedMeshCombiner), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_SkinnedMeshCombiner_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::SpriteCycle), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_SpriteCycle_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::SpriteCycleParallax), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_SpriteCycleParallax_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::TestMap), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_TestMap_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::UGUISpriteAnimation), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_UGUISpriteAnimation_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly5b193b5534114185a33ae42996dd4366::Anima2D.BlendShape), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly5b193b5534114185a33ae42996dd4366_Anima2D_BlendShape_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly5b193b5534114185a33ae42996dd4366::Anima2D.BlendShapeFrame), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly5b193b5534114185a33ae42996dd4366_Anima2D_BlendShapeFrame_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::Anima2D.Control), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_Anima2D_Control_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly5b193b5534114185a33ae42996dd4366::Anima2D.Edge), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly5b193b5534114185a33ae42996dd4366_Anima2D_Edge_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::Anima2D.EditorUpdaterProxy), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_Anima2D_EditorUpdaterProxy_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly5b193b5534114185a33ae42996dd4366::Anima2D.Node), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly5b193b5534114185a33ae42996dd4366_Anima2D_Node_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::Anima2D.Pose), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_Anima2D_Pose_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly5b193b5534114185a33ae42996dd4366::Anima2D.SerializedCache), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly5b193b5534114185a33ae42996dd4366_Anima2D_SerializedCache_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly5b193b5534114185a33ae42996dd4366::Anima2D.SpriteMeshCache), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly5b193b5534114185a33ae42996dd4366_Anima2D_SpriteMeshCache_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly5b193b5534114185a33ae42996dd4366::Anima2D.SpriteMeshData), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly5b193b5534114185a33ae42996dd4366_Anima2D_SpriteMeshData_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::Assets.Script.AI.Neural.Example), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_Assets_Script_AI_Neural_Example_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::Assets.Script.AI.Neural.Example2), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_Assets_Script_AI_Neural_Example2_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::UnityChan.SpringBone), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_UnityChan_SpringBone_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::UnityChan.SpringCollider), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_UnityChan_SpringCollider_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly4bd54c5c7a3f4920b37fe7d533cf59d9::UnityChan.SpringManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly4bd54c5c7a3f4920b37fe7d533cf59d9_UnityChan_SpringManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::AlphaButtonClickMask), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_AlphaButtonClickMask_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::EventSystemChecker), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_EventSystemChecker_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::ForcedReset), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_ForcedReset_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.AssetListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_AssetListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.BoxGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_BoxGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ButtonAndButtonGroupExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ButtonAndButtonGroupExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ColorPaletteExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ColorPaletteExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ContextExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ContextExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.CustomContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_CustomContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.CustomDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_CustomDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.CustomGroupExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_CustomGroupExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.DictionaryExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_DictionaryExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.DisableAndDisabledIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_DisableAndDisabledIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.DisableContextMenuExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_DisableContextMenuExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.DisableInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_DisableInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.DisplayAsStringExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_DisplayAsStringExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.EnumToggleButtonsExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_EnumToggleButtonsExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.FoldoutGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_FoldoutGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.GenericDrawerExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_GenericDrawerExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.GenericMenuExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_GenericMenuExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.GUIColorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_GUIColorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.HealthBarExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_HealthBarExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.HideInEditorAndPlayModeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_HideInEditorAndPlayModeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.HideLabelExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_HideLabelExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.HideReferenceObjectPickerExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_HideReferenceObjectPickerExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.HorizontalGroupAttributeExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_HorizontalGroupAttributeExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.IndentExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_IndentExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.InfoBoxExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_InfoBoxExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.InlineEditorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_InlineEditorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.LabelTextExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_LabelTextExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ListExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ListExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.MinMaxSliderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_MinMaxSliderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.MinMaxValueValueExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_MinMaxValueValueExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.MultiLinePropertyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_MultiLinePropertyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.NoBoilerplate), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_NoBoilerplate_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ObjectPlacer), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ObjectPlacer_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.OnInspectorGUIExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_OnInspectorGUIExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.OnValueChangedExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_OnValueChangedExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.PlaceableObject), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_PlaceableObject_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.PrefabOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_PrefabOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.PriorityExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_PriorityExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.PropertyOrderExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_PropertyOrderExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.PropertyTooltipExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_PropertyTooltipExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.QuaternionAndVectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_QuaternionAndVectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ReadOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ReadOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ReflectionExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ReflectionExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.RequiredExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_RequiredExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.SceneAndAssetsOnlyExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_SceneAndAssetsOnlyExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.SerializeAnything), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_SerializeAnything_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ShowAndHideIfExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ShowAndHideIfExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ShowInInspectorExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ShowInInspectorExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.TabExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_TabExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.TitleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_TitleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ToggleExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ToggleExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ToggleLeftExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ToggleLeftExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ValidateInputExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ValidateInputExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ValidationExample), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ValidationExample_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.ValueDropdownExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_ValueDropdownExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::Sirenix.OdinInspector.Demos.WrapExamples), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_Sirenix_OdinInspector_Demos_WrapExamples_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly6fa948118b9b4ba8a12ca777b979e390::Sirenix.OdinInspector.Editor.ColorPaletteManager), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly6fa948118b9b4ba8a12ca777b979e390_Sirenix_OdinInspector_Editor_ColorPaletteManager_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly6fa948118b9b4ba8a12ca777b979e390::Sirenix.OdinInspector.Editor.GeneralDrawerConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly6fa948118b9b4ba8a12ca777b979e390_Sirenix_OdinInspector_Editor_GeneralDrawerConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly6fa948118b9b4ba8a12ca777b979e390::Sirenix.OdinInspector.Editor.InspectorConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly6fa948118b9b4ba8a12ca777b979e390_Sirenix_OdinInspector_Editor_InspectorConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assembly6826020b926d45a5b887abb48d4934e7::Sirenix.Serialization.GlobalSerializationConfig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assembly6826020b926d45a5b887abb48d4934e7_Sirenix_Serialization_GlobalSerializationConfig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.CrossPlatformInput.AxisTouchButton), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_CrossPlatformInput_AxisTouchButton_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.CrossPlatformInput.ButtonHandler), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_CrossPlatformInput_ButtonHandler_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.CrossPlatformInput.InputAxisScrollbar), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_CrossPlatformInput_InputAxisScrollbar_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.CrossPlatformInput.Joystick), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_CrossPlatformInput_Joystick_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.CrossPlatformInput.MobileControlRig), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_CrossPlatformInput_MobileControlRig_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.CrossPlatformInput.TiltInput), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_CrossPlatformInput_TiltInput_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.CrossPlatformInput.TouchPad), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_CrossPlatformInput_TouchPad_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.ActivateTrigger), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_ActivateTrigger_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.AutoMobileShaderSwitch), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_AutoMobileShaderSwitch_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.AutoMoveAndRotate), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_AutoMoveAndRotate_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.DragRigidbody), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_DragRigidbody_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.DynamicShadowSettings), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_DynamicShadowSettings_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.FollowTarget), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_FollowTarget_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.FPSCounter), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_FPSCounter_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.ObjectResetter), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_ObjectResetter_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.ParticleSystemDestroyer), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_ParticleSystemDestroyer_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.PlatformSpecificContent), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_PlatformSpecificContent_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.SimpleActivatorMenu), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_SimpleActivatorMenu_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.SimpleMouseRotator), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_SimpleMouseRotator_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.SmoothFollow), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_SmoothFollow_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.TimedObjectActivator), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_TimedObjectActivator_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.TimedObjectDestructor), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_TimedObjectDestructor_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.WaypointCircuit), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_WaypointCircuit_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
    
    [CompilerGenerated]
    [CustomEditor(typeof(Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3::UnityStandardAssets.Utility.WaypointProgressTracker), false, isFallback = false)]
    [CanEditMultipleObjects]
    
    public sealed class Assemblyf2d364e2cd8d4d5a8af256a00d1cfbb3_UnityStandardAssets_Utility_WaypointProgressTracker_Editor : Sirenix.OdinInspector.Editor.OdinEditor
    {
    }
}
